language: ruby
rvm:
 - 2.7.0
install: bundle install

services:
  - postgresql

script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rails assets:precompile
  - bundle exec rspec
