language: ruby
rvm:
 - 2.7.0
 - 2.7.1
install: bundle install

services:
  - postgresql

script:
    - rails db:create RAILS_ENV=test
    - rails db:migrate RAILS_ENV=test
    - rspec spec/controllers
